import { Pokemon } from '../types/pokemon';

/**
 * Core Pokémon static mock dataset spanning all 9 generations.
 * Serves as an instant offline/fallback database for local exploration,
 * instant mini-games, and offline resilience.
 */
export const POKEMON_DATABASE: Pokemon[] = [
  // --- GENERATION 1: KANTO ---
  {
    id: 1,
    name: 'bulbasaur',
    displayName: 'Bulbasaur',
    aliases: ['bulbasaur', 'fushigidane'],
    generation: 1,
    types: ['grass', 'poison'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/1.ogg',
    height: 7,
    weight: 69,
    genus: 'Seed Pokémon',
    flavorText: 'A strange seed was planted on its back at birth. The plant sprouts and grows with this Pokémon.',
    stats: [
      { name: 'hp', baseStat: 45 },
      { name: 'attack', baseStat: 49 },
      { name: 'defense', baseStat: 49 },
      { name: 'special-attack', baseStat: 65 },
      { name: 'special-defense', baseStat: 65 },
      { name: 'speed', baseStat: 45 },
    ],
    abilities: [
      { name: 'Overgrow', isHidden: false },
      { name: 'Chlorophyll', isHidden: true },
    ],
  },
  {
    id: 2,
    name: 'ivysaur',
    displayName: 'Ivysaur',
    aliases: ['ivysaur'],
    generation: 1,
    types: ['grass', 'poison'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/2.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/2.ogg',
    height: 10,
    weight: 130,
    genus: 'Seed Pokémon',
    flavorText: 'When the bud on its back starts swelling, a sweet aroma wafts to indicate the flowers coming bloom.',
    stats: [
      { name: 'hp', baseStat: 60 },
      { name: 'attack', baseStat: 62 },
      { name: 'defense', baseStat: 63 },
      { name: 'special-attack', baseStat: 80 },
      { name: 'special-defense', baseStat: 80 },
      { name: 'speed', baseStat: 60 },
    ],
    abilities: [
      { name: 'Overgrow', isHidden: false },
      { name: 'Chlorophyll', isHidden: true },
    ],
  },
  {
    id: 3,
    name: 'venusaur',
    displayName: 'Venusaur',
    aliases: ['venusaur'],
    generation: 1,
    types: ['grass', 'poison'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/3.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/3.ogg',
    height: 20,
    weight: 1000,
    genus: 'Seed Pokémon',
    flavorText: 'By spreading the broad petals of its flower and catching the sun, it fills its body with power.',
    stats: [
      { name: 'hp', baseStat: 80 },
      { name: 'attack', baseStat: 82 },
      { name: 'defense', baseStat: 83 },
      { name: 'special-attack', baseStat: 100 },
      { name: 'special-defense', baseStat: 100 },
      { name: 'speed', baseStat: 80 },
    ],
    abilities: [
      { name: 'Overgrow', isHidden: false },
      { name: 'Chlorophyll', isHidden: true },
    ],
  },
  {
    id: 4,
    name: 'charmander',
    displayName: 'Charmander',
    aliases: ['charmander', 'hitokage'],
    generation: 1,
    types: ['fire'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/4.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/4.ogg',
    height: 6,
    weight: 85,
    genus: 'Lizard Pokémon',
    flavorText: 'The flame on its tail indicates Charmander’s life force. It burns vigorously when healthy.',
    stats: [
      { name: 'hp', baseStat: 39 },
      { name: 'attack', baseStat: 52 },
      { name: 'defense', baseStat: 43 },
      { name: 'special-attack', baseStat: 60 },
      { name: 'special-defense', baseStat: 50 },
      { name: 'speed', baseStat: 65 },
    ],
    abilities: [
      { name: 'Blaze', isHidden: false },
      { name: 'Solar Power', isHidden: true },
    ],
  },
  {
    id: 5,
    name: 'charmeleon',
    displayName: 'Charmeleon',
    aliases: ['charmeleon'],
    generation: 1,
    types: ['fire'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/5.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/5.ogg',
    height: 11,
    weight: 190,
    genus: 'Flame Pokémon',
    flavorText: 'When it swings its burning tail, it elevates the temperature to unbearably high levels.',
    stats: [
      { name: 'hp', baseStat: 58 },
      { name: 'attack', baseStat: 64 },
      { name: 'defense', baseStat: 58 },
      { name: 'special-attack', baseStat: 80 },
      { name: 'special-defense', baseStat: 65 },
      { name: 'speed', baseStat: 80 },
    ],
    abilities: [
      { name: 'Blaze', isHidden: false },
      { name: 'Solar Power', isHidden: true },
    ],
  },
  {
    id: 6,
    name: 'charizard',
    displayName: 'Charizard',
    aliases: ['charizard', 'lizardon'],
    generation: 1,
    types: ['fire', 'flying'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/6.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/6.ogg',
    height: 17,
    weight: 905,
    genus: 'Flame Pokémon',
    flavorText: 'Spits fire that is hot enough to melt boulders. Known to cause forest fires unintentionally.',
    stats: [
      { name: 'hp', baseStat: 78 },
      { name: 'attack', baseStat: 84 },
      { name: 'defense', baseStat: 78 },
      { name: 'special-attack', baseStat: 109 },
      { name: 'special-defense', baseStat: 85 },
      { name: 'speed', baseStat: 100 },
    ],
    abilities: [
      { name: 'Blaze', isHidden: false },
      { name: 'Solar Power', isHidden: true },
    ],
  },
  {
    id: 7,
    name: 'squirtle',
    displayName: 'Squirtle',
    aliases: ['squirtle', 'zenigame'],
    generation: 1,
    types: ['water'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/7.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/7.ogg',
    height: 5,
    weight: 90,
    genus: 'Tiny Turtle Pokémon',
    flavorText: 'Shoots water at prey while in the water. Withdraws into its shell when in danger.',
    stats: [
      { name: 'hp', baseStat: 44 },
      { name: 'attack', baseStat: 48 },
      { name: 'defense', baseStat: 65 },
      { name: 'special-attack', baseStat: 50 },
      { name: 'special-defense', baseStat: 64 },
      { name: 'speed', baseStat: 43 },
    ],
    abilities: [
      { name: 'Torrent', isHidden: false },
      { name: 'Rain Dish', isHidden: true },
    ],
  },
  {
    id: 8,
    name: 'wartortle',
    displayName: 'Wartortle',
    aliases: ['wartortle'],
    generation: 1,
    types: ['water'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/8.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/8.ogg',
    height: 10,
    weight: 225,
    genus: 'Turtle Pokémon',
    flavorText: 'Often recognized as a symbol of longevity. If its shell has algae on it, that Wartortle is very old.',
    stats: [
      { name: 'hp', baseStat: 59 },
      { name: 'attack', baseStat: 63 },
      { name: 'defense', baseStat: 80 },
      { name: 'special-attack', baseStat: 65 },
      { name: 'special-defense', baseStat: 80 },
      { name: 'speed', baseStat: 58 },
    ],
    abilities: [
      { name: 'Torrent', isHidden: false },
      { name: 'Rain Dish', isHidden: true },
    ],
  },
  {
    id: 9,
    name: 'blastoise',
    displayName: 'Blastoise',
    aliases: ['blastoise'],
    generation: 1,
    types: ['water'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/9.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/9.ogg',
    height: 16,
    weight: 855,
    genus: 'Shellfish Pokémon',
    flavorText: 'The rocket cannons on its shell fire water spouts capable of punching holes through thick steel.',
    stats: [
      { name: 'hp', baseStat: 79 },
      { name: 'attack', baseStat: 83 },
      { name: 'defense', baseStat: 100 },
      { name: 'special-attack', baseStat: 85 },
      { name: 'special-defense', baseStat: 105 },
      { name: 'speed', baseStat: 78 },
    ],
    abilities: [
      { name: 'Torrent', isHidden: false },
      { name: 'Rain Dish', isHidden: true },
    ],
  },
  {
    id: 25,
    name: 'pikachu',
    displayName: 'Pikachu',
    aliases: ['pikachu'],
    generation: 1,
    types: ['electric'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/25.ogg',
    height: 4,
    weight: 60,
    genus: 'Mouse Pokémon',
    flavorText: 'When several of these Pokémon gather, their electricity could build and cause lightning storms.',
    stats: [
      { name: 'hp', baseStat: 35 },
      { name: 'attack', baseStat: 55 },
      { name: 'defense', baseStat: 40 },
      { name: 'special-attack', baseStat: 50 },
      { name: 'special-defense', baseStat: 50 },
      { name: 'speed', baseStat: 90 },
    ],
    abilities: [
      { name: 'Static', isHidden: false },
      { name: 'Lightning Rod', isHidden: true },
    ],
  },
  // SPECIAL CANONICAL MULTI-MATCH: Nidoran (Female & Male)
  {
    id: 29,
    name: 'nidoran-f',
    displayName: 'Nidoran♀',
    aliases: ['nidoran', 'nidoran f', 'nidoran female', 'nidoran-f'],
    generation: 1,
    types: ['poison'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/29.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/29.ogg',
    height: 4,
    weight: 70,
    genus: 'Poison Pin Pokémon',
    flavorText: 'Although small, its venomous barbs render this Pokémon dangerous. The female has smaller horns.',
    stats: [
      { name: 'hp', baseStat: 55 },
      { name: 'attack', baseStat: 47 },
      { name: 'defense', baseStat: 52 },
      { name: 'special-attack', baseStat: 40 },
      { name: 'special-defense', baseStat: 40 },
      { name: 'speed', baseStat: 41 },
    ],
    abilities: [
      { name: 'Poison Point', isHidden: false },
      { name: 'Rivalry', isHidden: false },
      { name: 'Hustle', isHidden: true },
    ],
  },
  {
    id: 32,
    name: 'nidoran-m',
    displayName: 'Nidoran♂',
    aliases: ['nidoran', 'nidoran m', 'nidoran male', 'nidoran-m'],
    generation: 1,
    types: ['poison'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/32.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/32.ogg',
    height: 5,
    weight: 90,
    genus: 'Poison Pin Pokémon',
    flavorText: 'Stiffens its ears to detect any sound. If it senses danger, it attacks with its venomous horn.',
    stats: [
      { name: 'hp', baseStat: 46 },
      { name: 'attack', baseStat: 56 },
      { name: 'defense', baseStat: 40 },
      { name: 'special-attack', baseStat: 40 },
      { name: 'special-defense', baseStat: 40 },
      { name: 'speed', baseStat: 50 },
    ],
    abilities: [
      { name: 'Poison Point', isHidden: false },
      { name: 'Rivalry', isHidden: false },
      { name: 'Hustle', isHidden: true },
    ],
  },
  // SPECIAL MULTI-MATCH / REGIONAL VARIANT EXAMPLE: Tauros
  {
    id: 128,
    name: 'tauros',
    displayName: 'Tauros',
    aliases: ['tauros', 'kantonian tauros', 'paldean tauros'],
    generation: 1,
    types: ['normal'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/128.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/128.ogg',
    height: 14,
    weight: 884,
    genus: 'Wild Bull Pokémon',
    flavorText: 'When it targets an enemy, it charges furiously while whipping its body with its long tails.',
    stats: [
      { name: 'hp', baseStat: 75 },
      { name: 'attack', baseStat: 100 },
      { name: 'defense', baseStat: 95 },
      { name: 'special-attack', baseStat: 40 },
      { name: 'special-defense', baseStat: 70 },
      { name: 'speed', baseStat: 110 },
    ],
    abilities: [
      { name: 'Intimidate', isHidden: false },
      { name: 'Anger Point', isHidden: false },
      { name: 'Sheer Force', isHidden: true },
    ],
  },
  // SPECIAL PUNCTUATION / SPACE VARIATIONS
  {
    id: 122,
    name: 'mr-mime',
    displayName: 'Mr. Mime',
    aliases: ['mr. mime', 'mr mime', 'mrmime'],
    generation: 1,
    types: ['psychic', 'fairy'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/122.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/122.ogg',
    height: 13,
    weight: 545,
    genus: 'Barrier Pokémon',
    flavorText: 'If interrupted while miming, it will slappedly berate the offender with its broad hands.',
    stats: [
      { name: 'hp', baseStat: 40 },
      { name: 'attack', baseStat: 45 },
      { name: 'defense', baseStat: 65 },
      { name: 'special-attack', baseStat: 100 },
      { name: 'special-defense', baseStat: 120 },
      { name: 'speed', baseStat: 90 },
    ],
    abilities: [
      { name: 'Soundproof', isHidden: false },
      { name: 'Filter', isHidden: false },
    ],
  },
  {
    id: 133,
    name: 'eevee',
    displayName: 'Eevee',
    aliases: ['eevee'],
    generation: 1,
    types: ['normal'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/133.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/133.ogg',
    height: 3,
    weight: 65,
    genus: 'Evolution Pokémon',
    flavorText: 'Its genetic code is irregular. It may mutate if it is exposed to radiation from element stones.',
    stats: [
      { name: 'hp', baseStat: 55 },
      { name: 'attack', baseStat: 55 },
      { name: 'defense', baseStat: 50 },
      { name: 'special-attack', baseStat: 45 },
      { name: 'special-defense', baseStat: 65 },
      { name: 'speed', baseStat: 55 },
    ],
    abilities: [
      { name: 'Run Away', isHidden: false },
      { name: 'Adaptability', isHidden: false },
      { name: 'Anticipation', isHidden: true },
    ],
  },
  {
    id: 143,
    name: 'snorlax',
    displayName: 'Snorlax',
    aliases: ['snorlax', 'kabigon'],
    generation: 1,
    types: ['normal'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/143.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/143.ogg',
    height: 21,
    weight: 4600,
    genus: 'Sleeping Pokémon',
    flavorText: 'Very lazy. Just eats and sleeps. As its enormous bulk builds, it becomes even more reluctant to move.',
    stats: [
      { name: 'hp', baseStat: 160 },
      { name: 'attack', baseStat: 110 },
      { name: 'defense', baseStat: 65 },
      { name: 'special-attack', baseStat: 65 },
      { name: 'special-defense', baseStat: 110 },
      { name: 'speed', baseStat: 30 },
    ],
    abilities: [
      { name: 'Immunity', isHidden: false },
      { name: 'Thick Fat', isHidden: false },
      { name: 'Gluttony', isHidden: true },
    ],
  },
  {
    id: 150,
    name: 'mewtwo',
    displayName: 'Mewtwo',
    aliases: ['mewtwo'],
    generation: 1,
    types: ['psychic'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/150.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/150.ogg',
    height: 20,
    weight: 1220,
    genus: 'Genetic Pokémon',
    flavorText: 'It was created by a scientist after years of horrific gene splicing and DNA engineering experiments.',
    isLegendary: true,
    stats: [
      { name: 'hp', baseStat: 106 },
      { name: 'attack', baseStat: 110 },
      { name: 'defense', baseStat: 90 },
      { name: 'special-attack', baseStat: 154 },
      { name: 'special-defense', baseStat: 90 },
      { name: 'speed', baseStat: 130 },
    ],
    abilities: [{ name: 'Pressure', isHidden: false }],
  },
  {
    id: 151,
    name: 'mew',
    displayName: 'Mew',
    aliases: ['mew'],
    generation: 1,
    types: ['psychic'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/151.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/151.ogg',
    height: 4,
    weight: 40,
    genus: 'New Species Pokémon',
    flavorText: 'So rare that it is still said to be a mirage by many experts. Only a few people have seen it.',
    isMythical: true,
    stats: [
      { name: 'hp', baseStat: 100 },
      { name: 'attack', baseStat: 100 },
      { name: 'defense', baseStat: 100 },
      { name: 'special-attack', baseStat: 100 },
      { name: 'special-defense', baseStat: 100 },
      { name: 'speed', baseStat: 100 },
    ],
    abilities: [{ name: 'Synchronize', isHidden: false }],
  },

  // --- GENERATION 2: JOHTO ---
  {
    id: 152,
    name: 'chikorita',
    displayName: 'Chikorita',
    aliases: ['chikorita'],
    generation: 2,
    types: ['grass'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/152.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/152.ogg',
    height: 9,
    weight: 64,
    genus: 'Leaf Pokémon',
    flavorText: 'A sweet aroma gently wafts from the leaf on its head. It is docile and loves to soak up the suns rays.',
    stats: [
      { name: 'hp', baseStat: 45 },
      { name: 'attack', baseStat: 49 },
      { name: 'defense', baseStat: 65 },
      { name: 'special-attack', baseStat: 49 },
      { name: 'special-defense', baseStat: 65 },
      { name: 'speed', baseStat: 45 },
    ],
    abilities: [{ name: 'Overgrow', isHidden: false }],
  },
  {
    id: 155,
    name: 'cyndaquil',
    displayName: 'Cyndaquil',
    aliases: ['cyndaquil'],
    generation: 2,
    types: ['fire'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/155.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/155.ogg',
    height: 5,
    weight: 79,
    genus: 'Fire Mouse Pokémon',
    flavorText: 'It is timid, and always curls itself up into a ball. If attacked, it flares up its back for protection.',
    stats: [
      { name: 'hp', baseStat: 39 },
      { name: 'attack', baseStat: 52 },
      { name: 'defense', baseStat: 43 },
      { name: 'special-attack', baseStat: 60 },
      { name: 'special-defense', baseStat: 50 },
      { name: 'speed', baseStat: 65 },
    ],
    abilities: [{ name: 'Blaze', isHidden: false }],
  },
  {
    id: 158,
    name: 'totodile',
    displayName: 'Totodile',
    aliases: ['totodile'],
    generation: 2,
    types: ['water'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/158.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/158.ogg',
    height: 6,
    weight: 95,
    genus: 'Big Jaw Pokémon',
    flavorText: 'Its well-developed jaws are powerful and capable of crushing anything. Even its trainer must be careful.',
    stats: [
      { name: 'hp', baseStat: 50 },
      { name: 'attack', baseStat: 65 },
      { name: 'defense', baseStat: 64 },
      { name: 'special-attack', baseStat: 44 },
      { name: 'special-defense', baseStat: 48 },
      { name: 'speed', baseStat: 43 },
    ],
    abilities: [{ name: 'Torrent', isHidden: false }],
  },
  {
    id: 249,
    name: 'lugia',
    displayName: 'Lugia',
    aliases: ['lugia'],
    generation: 2,
    types: ['psychic', 'flying'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/249.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/249.ogg',
    height: 52,
    weight: 2160,
    genus: 'Diving Pokémon',
    flavorText: 'It sleeps in a deep-sea trench. If it flaps its wings, it is said to cause a 40-day storm.',
    isLegendary: true,
    stats: [
      { name: 'hp', baseStat: 106 },
      { name: 'attack', baseStat: 90 },
      { name: 'defense', baseStat: 130 },
      { name: 'special-attack', baseStat: 90 },
      { name: 'special-defense', baseStat: 154 },
      { name: 'speed', baseStat: 110 },
    ],
    abilities: [{ name: 'Pressure', isHidden: false }],
  },
  {
    id: 250,
    name: 'ho-oh',
    displayName: 'Ho-Oh',
    aliases: ['ho-oh', 'ho oh', 'hooh'],
    generation: 2,
    types: ['fire', 'flying'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/250.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/250.ogg',
    height: 38,
    weight: 1990,
    genus: 'Rainbow Pokémon',
    flavorText: 'A legend says that its body glows in seven colors. A rainbow is said to form behind it when it flies.',
    isLegendary: true,
    stats: [
      { name: 'hp', baseStat: 106 },
      { name: 'attack', baseStat: 130 },
      { name: 'defense', baseStat: 90 },
      { name: 'special-attack', baseStat: 110 },
      { name: 'special-defense', baseStat: 154 },
      { name: 'speed', baseStat: 90 },
    ],
    abilities: [{ name: 'Pressure', isHidden: false }],
  },

  // --- GENERATION 3: HOENN ---
  {
    id: 252,
    name: 'treecko',
    displayName: 'Treecko',
    aliases: ['treecko'],
    generation: 3,
    types: ['grass'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/252.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/252.ogg',
    height: 5,
    weight: 50,
    genus: 'Wood Gecko Pokémon',
    flavorText: 'The soles of its feet are covered with countless tiny spikes, enabling it to walk on walls and ceilings.',
    stats: [
      { name: 'hp', baseStat: 40 },
      { name: 'attack', baseStat: 45 },
      { name: 'defense', baseStat: 35 },
      { name: 'special-attack', baseStat: 65 },
      { name: 'special-defense', baseStat: 55 },
      { name: 'speed', baseStat: 70 },
    ],
    abilities: [{ name: 'Overgrow', isHidden: false }],
  },
  {
    id: 255,
    name: 'torchic',
    displayName: 'Torchic',
    aliases: ['torchic'],
    generation: 3,
    types: ['fire'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/255.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/255.ogg',
    height: 4,
    weight: 25,
    genus: 'Chick Pokémon',
    flavorText: 'A fire burns inside, so it feels very warm to hug. It launches fireballs of 1,800 degrees F.',
    stats: [
      { name: 'hp', baseStat: 45 },
      { name: 'attack', baseStat: 60 },
      { name: 'defense', baseStat: 40 },
      { name: 'special-attack', baseStat: 70 },
      { name: 'special-defense', baseStat: 50 },
      { name: 'speed', baseStat: 45 },
    ],
    abilities: [{ name: 'Blaze', isHidden: false }],
  },
  {
    id: 258,
    name: 'mudkip',
    displayName: 'Mudkip',
    aliases: ['mudkip'],
    generation: 3,
    types: ['water'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/258.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/258.ogg',
    height: 4,
    weight: 76,
    genus: 'Mud Fish Pokémon',
    flavorText: 'The fin on Mudkip’s head acts as highly sensitive radar. Using it, it can sense movements without sight.',
    stats: [
      { name: 'hp', baseStat: 50 },
      { name: 'attack', baseStat: 70 },
      { name: 'defense', baseStat: 50 },
      { name: 'special-attack', baseStat: 50 },
      { name: 'special-defense', baseStat: 50 },
      { name: 'speed', baseStat: 40 },
    ],
    abilities: [{ name: 'Torrent', isHidden: false }],
  },
  {
    id: 384,
    name: 'rayquaza',
    displayName: 'Rayquaza',
    aliases: ['rayquaza'],
    generation: 3,
    types: ['dragon', 'flying'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/384.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/384.ogg',
    height: 70,
    weight: 2065,
    genus: 'Sky High Pokémon',
    flavorText: 'It has lived for hundreds of millions of years in the ozone layer. Its existence was long unknown.',
    isLegendary: true,
    stats: [
      { name: 'hp', baseStat: 105 },
      { name: 'attack', baseStat: 150 },
      { name: 'defense', baseStat: 90 },
      { name: 'special-attack', baseStat: 150 },
      { name: 'special-defense', baseStat: 90 },
      { name: 'speed', baseStat: 95 },
    ],
    abilities: [{ name: 'Air Lock', isHidden: false }],
  },

  // --- GENERATION 4: SINNOH ---
  {
    id: 387,
    name: 'turtwig',
    displayName: 'Turtwig',
    aliases: ['turtwig'],
    generation: 4,
    types: ['grass'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/387.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/387.ogg',
    height: 4,
    weight: 102,
    genus: 'Tiny Leaf Pokémon',
    flavorText: 'Made from soil, the shell on its back hardens when it drinks water. It lives along lakes.',
    stats: [
      { name: 'hp', baseStat: 55 },
      { name: 'attack', baseStat: 68 },
      { name: 'defense', baseStat: 64 },
      { name: 'special-attack', baseStat: 45 },
      { name: 'special-defense', baseStat: 55 },
      { name: 'speed', baseStat: 31 },
    ],
    abilities: [{ name: 'Overgrow', isHidden: false }],
  },
  {
    id: 390,
    name: 'chimchar',
    displayName: 'Chimchar',
    aliases: ['chimchar'],
    generation: 4,
    types: ['fire'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/390.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/390.ogg',
    height: 5,
    weight: 64,
    genus: 'Chimp Pokémon',
    flavorText: 'It agilely scales sheer cliffs to live atop rocky mountains. Its fiery tail never burns out in rain.',
    stats: [
      { name: 'hp', baseStat: 44 },
      { name: 'attack', baseStat: 58 },
      { name: 'defense', baseStat: 44 },
      { name: 'special-attack', baseStat: 58 },
      { name: 'special-defense', baseStat: 44 },
      { name: 'speed', baseStat: 61 },
    ],
    abilities: [{ name: 'Blaze', isHidden: false }],
  },
  {
    id: 393,
    name: 'piplup',
    displayName: 'Piplup',
    aliases: ['piplup'],
    generation: 4,
    types: ['water'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/393.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/393.ogg',
    height: 4,
    weight: 52,
    genus: 'Penguin Pokémon',
    flavorText: 'Because it is very proud, it hates accepting food from people. Its thick down shields it from cold.',
    stats: [
      { name: 'hp', baseStat: 53 },
      { name: 'attack', baseStat: 51 },
      { name: 'defense', baseStat: 53 },
      { name: 'special-attack', baseStat: 61 },
      { name: 'special-defense', baseStat: 56 },
      { name: 'speed', baseStat: 40 },
    ],
    abilities: [{ name: 'Torrent', isHidden: false }],
  },
  {
    id: 448,
    name: 'lucario',
    displayName: 'Lucario',
    aliases: ['lucario'],
    generation: 4,
    types: ['fighting', 'steel'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/448.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/448.ogg',
    height: 12,
    weight: 540,
    genus: 'Aura Pokémon',
    flavorText: 'By catching the aura emanating from others, it can read their thoughts and movements.',
    stats: [
      { name: 'hp', baseStat: 70 },
      { name: 'attack', baseStat: 110 },
      { name: 'defense', baseStat: 70 },
      { name: 'special-attack', baseStat: 115 },
      { name: 'special-defense', baseStat: 70 },
      { name: 'speed', baseStat: 90 },
    ],
    abilities: [{ name: 'Steadfast', isHidden: false }, { name: 'Inner Focus', isHidden: false }],
  },
  // SPECIAL EXPLICIT SPEC EXAMPLE: Porygon-Z
  {
    id: 474,
    name: 'porygon-z',
    displayName: 'Porygon-Z',
    aliases: ['porygon-z', 'porygon z', 'porygonz'],
    generation: 4,
    types: ['normal'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/474.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/474.ogg',
    height: 9,
    weight: 340,
    genus: 'Virtual Pokémon',
    flavorText: 'Additional software was installed to make it a better Pokémon. It began acting oddly, however.',
    stats: [
      { name: 'hp', baseStat: 85 },
      { name: 'attack', baseStat: 80 },
      { name: 'defense', baseStat: 70 },
      { name: 'special-attack', baseStat: 135 },
      { name: 'special-defense', baseStat: 75 },
      { name: 'speed', baseStat: 90 },
    ],
    abilities: [
      { name: 'Adaptability', isHidden: false },
      { name: 'Download', isHidden: false },
      { name: 'Analytic', isHidden: true },
    ],
  },
  {
    id: 493,
    name: 'arceus',
    displayName: 'Arceus',
    aliases: ['arceus'],
    generation: 4,
    types: ['normal'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/493.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/493.ogg',
    height: 32,
    weight: 3200,
    genus: 'Alpha Pokémon',
    flavorText: 'It is told in mythology that this Pokémon was born before the universe even existed.',
    isMythical: true,
    stats: [
      { name: 'hp', baseStat: 120 },
      { name: 'attack', baseStat: 120 },
      { name: 'defense', baseStat: 120 },
      { name: 'special-attack', baseStat: 120 },
      { name: 'special-defense', baseStat: 120 },
      { name: 'speed', baseStat: 120 },
    ],
    abilities: [{ name: 'Multitype', isHidden: false }],
  },

  // --- GENERATION 5: UNOVA ---
  {
    id: 494,
    name: 'victini',
    displayName: 'Victini',
    aliases: ['victini'],
    generation: 5,
    types: ['psychic', 'fire'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/494.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/494.ogg',
    height: 4,
    weight: 40,
    genus: 'Victory Pokémon',
    flavorText: 'This Pokémon brings victory. It is said that Trainers with Victini always win, regardless of type.',
    isMythical: true,
    stats: [
      { name: 'hp', baseStat: 100 },
      { name: 'attack', baseStat: 100 },
      { name: 'defense', baseStat: 100 },
      { name: 'special-attack', baseStat: 100 },
      { name: 'special-defense', baseStat: 100 },
      { name: 'speed', baseStat: 100 },
    ],
    abilities: [{ name: 'Victory Star', isHidden: false }],
  },
  {
    id: 495,
    name: 'snivy',
    displayName: 'Snivy',
    aliases: ['snivy'],
    generation: 5,
    types: ['grass'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/495.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/495.ogg',
    height: 6,
    weight: 81,
    genus: 'Grass Snake Pokémon',
    flavorText: 'They photosynthesize by bathing their tails in sunlight. When they are not feeling well, their tails droop.',
    stats: [
      { name: 'hp', baseStat: 45 },
      { name: 'attack', baseStat: 45 },
      { name: 'defense', baseStat: 55 },
      { name: 'special-attack', baseStat: 45 },
      { name: 'special-defense', baseStat: 55 },
      { name: 'speed', baseStat: 63 },
    ],
    abilities: [{ name: 'Overgrow', isHidden: false }],
  },
  {
    id: 498,
    name: 'tepig',
    displayName: 'Tepig',
    aliases: ['tepig'],
    generation: 5,
    types: ['fire'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/498.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/498.ogg',
    height: 5,
    weight: 99,
    genus: 'Fire Pig Pokémon',
    flavorText: 'It can deftly dodge its foe’s attacks while shooting fireballs from its nose. It roasts berries before eating them.',
    stats: [
      { name: 'hp', baseStat: 65 },
      { name: 'attack', baseStat: 63 },
      { name: 'defense', baseStat: 45 },
      { name: 'special-attack', baseStat: 45 },
      { name: 'special-defense', baseStat: 45 },
      { name: 'speed', baseStat: 45 },
    ],
    abilities: [{ name: 'Blaze', isHidden: false }],
  },
  {
    id: 501,
    name: 'oshawott',
    displayName: 'Oshawott',
    aliases: ['oshawott'],
    generation: 5,
    types: ['water'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/501.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/501.ogg',
    height: 5,
    weight: 59,
    genus: 'Sea Otter Pokémon',
    flavorText: 'The scalchop on its stomach isn’t just for attacking; it can be used for breaking open hard berries as well.',
    stats: [
      { name: 'hp', baseStat: 55 },
      { name: 'attack', baseStat: 55 },
      { name: 'defense', baseStat: 45 },
      { name: 'special-attack', baseStat: 63 },
      { name: 'special-defense', baseStat: 45 },
      { name: 'speed', baseStat: 45 },
    ],
    abilities: [{ name: 'Torrent', isHidden: false }],
  },
  {
    id: 571,
    name: 'zoroark',
    displayName: 'Zoroark',
    aliases: ['zoroark'],
    generation: 5,
    types: ['dark'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/571.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/571.ogg',
    height: 16,
    weight: 811,
    genus: 'Illusion Fox Pokémon',
    flavorText: 'Bonds between these Pokémon are very strong. It protects the safety of its pack by tricking opponents.',
    stats: [
      { name: 'hp', baseStat: 60 },
      { name: 'attack', baseStat: 105 },
      { name: 'defense', baseStat: 60 },
      { name: 'special-attack', baseStat: 120 },
      { name: 'special-defense', baseStat: 60 },
      { name: 'speed', baseStat: 105 },
    ],
    abilities: [{ name: 'Illusion', isHidden: false }],
  },

  // --- GENERATION 6: KALOS ---
  {
    id: 650,
    name: 'chespin',
    displayName: 'Chespin',
    aliases: ['chespin'],
    generation: 6,
    types: ['grass'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/650.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/650.ogg',
    height: 4,
    weight: 90,
    genus: 'Spiny Nut Pokémon',
    flavorText: 'The quills on its head are usually soft. When it flexes them, the points become sharp and needle-like.',
    stats: [
      { name: 'hp', baseStat: 56 },
      { name: 'attack', baseStat: 61 },
      { name: 'defense', baseStat: 65 },
      { name: 'special-attack', baseStat: 48 },
      { name: 'special-defense', baseStat: 45 },
      { name: 'speed', baseStat: 38 },
    ],
    abilities: [{ name: 'Overgrow', isHidden: false }],
  },
  {
    id: 653,
    name: 'fennekin',
    displayName: 'Fennekin',
    aliases: ['fennekin'],
    generation: 6,
    types: ['fire'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/653.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/653.ogg',
    height: 4,
    weight: 94,
    genus: 'Fox Pokémon',
    flavorText: 'Eating a twig fills it with energy, and its roomy ears give vent to air hotter than 390 degrees F.',
    stats: [
      { name: 'hp', baseStat: 40 },
      { name: 'attack', baseStat: 45 },
      { name: 'defense', baseStat: 40 },
      { name: 'special-attack', baseStat: 62 },
      { name: 'special-defense', baseStat: 60 },
      { name: 'speed', baseStat: 60 },
    ],
    abilities: [{ name: 'Blaze', isHidden: false }],
  },
  {
    id: 656,
    name: 'froakie',
    displayName: 'Froakie',
    aliases: ['froakie'],
    generation: 6,
    types: ['water'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/656.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/656.ogg',
    height: 3,
    weight: 70,
    genus: 'Bubble Frog Pokémon',
    flavorText: 'It secretes delicate bubbles from its chest and back. The bubbles reduce damage it would otherwise take.',
    stats: [
      { name: 'hp', baseStat: 41 },
      { name: 'attack', baseStat: 56 },
      { name: 'defense', baseStat: 40 },
      { name: 'special-attack', baseStat: 62 },
      { name: 'special-defense', baseStat: 44 },
      { name: 'speed', baseStat: 71 },
    ],
    abilities: [{ name: 'Torrent', isHidden: false }],
  },
  {
    id: 658,
    name: 'greninja',
    displayName: 'Greninja',
    aliases: ['greninja'],
    generation: 6,
    types: ['water', 'dark'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/658.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/658.ogg',
    height: 15,
    weight: 400,
    genus: 'Ninja Pokémon',
    flavorText: 'It creates throwing stars out of compressed water. When it spins them and throws them, they can slice metal.',
    stats: [
      { name: 'hp', baseStat: 72 },
      { name: 'attack', baseStat: 95 },
      { name: 'defense', baseStat: 67 },
      { name: 'special-attack', baseStat: 103 },
      { name: 'special-defense', baseStat: 71 },
      { name: 'speed', baseStat: 122 },
    ],
    abilities: [{ name: 'Torrent', isHidden: false }, { name: 'Protean', isHidden: true }],
  },
  {
    id: 669,
    name: 'flabebe',
    displayName: 'Flabébé',
    aliases: ['flabebe', 'flabébé'],
    generation: 6,
    types: ['fairy'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/669.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/669.ogg',
    height: 1,
    weight: 1,
    genus: 'Single Bloom Pokémon',
    flavorText: 'It draws forth and shares the hidden power of flowers. The blossom on which it sits is like part of its body.',
    stats: [
      { name: 'hp', baseStat: 44 },
      { name: 'attack', baseStat: 38 },
      { name: 'defense', baseStat: 39 },
      { name: 'special-attack', baseStat: 61 },
      { name: 'special-defense', baseStat: 79 },
      { name: 'speed', baseStat: 42 },
    ],
    abilities: [{ name: 'Flower Veil', isHidden: false }],
  },

  // --- GENERATION 7: ALOLA ---
  {
    id: 722,
    name: 'rowlet',
    displayName: 'Rowlet',
    aliases: ['rowlet'],
    generation: 7,
    types: ['grass', 'flying'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/722.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/722.ogg',
    height: 3,
    weight: 15,
    genus: 'Grass Quill Pokémon',
    flavorText: 'Silently it glides, drawing near its targets. Before they notice it, it begins to pelt them with feathers.',
    stats: [
      { name: 'hp', baseStat: 68 },
      { name: 'attack', baseStat: 55 },
      { name: 'defense', baseStat: 55 },
      { name: 'special-attack', baseStat: 50 },
      { name: 'special-defense', baseStat: 50 },
      { name: 'speed', baseStat: 42 },
    ],
    abilities: [{ name: 'Overgrow', isHidden: false }],
  },
  {
    id: 725,
    name: 'litten',
    displayName: 'Litten',
    aliases: ['litten'],
    generation: 7,
    types: ['fire'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/725.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/725.ogg',
    height: 4,
    weight: 43,
    genus: 'Fire Cat Pokémon',
    flavorText: 'While grooming itself, it builds up fur inside its stomach. It sets the fur on fire and spews fiery attacks.',
    stats: [
      { name: 'hp', baseStat: 45 },
      { name: 'attack', baseStat: 65 },
      { name: 'defense', baseStat: 40 },
      { name: 'special-attack', baseStat: 60 },
      { name: 'special-defense', baseStat: 40 },
      { name: 'speed', baseStat: 70 },
    ],
    abilities: [{ name: 'Blaze', isHidden: false }],
  },
  {
    id: 728,
    name: 'popplio',
    displayName: 'Popplio',
    aliases: ['popplio'],
    generation: 7,
    types: ['water'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/728.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/728.ogg',
    height: 4,
    weight: 75,
    genus: 'Sea Lion Pokémon',
    flavorText: 'This Pokémon can inflate water balloons with its nose and spin them playfully in battle.',
    stats: [
      { name: 'hp', baseStat: 50 },
      { name: 'attack', baseStat: 54 },
      { name: 'defense', baseStat: 54 },
      { name: 'special-attack', baseStat: 66 },
      { name: 'special-defense', baseStat: 56 },
      { name: 'speed', baseStat: 40 },
    ],
    abilities: [{ name: 'Torrent', isHidden: false }],
  },
  {
    id: 778,
    name: 'mimikyu',
    displayName: 'Mimikyu',
    aliases: ['mimikyu'],
    generation: 7,
    types: ['ghost', 'fairy'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/778.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/778.ogg',
    height: 2,
    weight: 7,
    genus: 'Disguise Pokémon',
    flavorText: 'It wears a ragged rag fashioned like a Pikachu because it desires to be loved like Pikachu.',
    stats: [
      { name: 'hp', baseStat: 55 },
      { name: 'attack', baseStat: 90 },
      { name: 'defense', baseStat: 80 },
      { name: 'special-attack', baseStat: 50 },
      { name: 'special-defense', baseStat: 105 },
      { name: 'speed', baseStat: 96 },
    ],
    abilities: [{ name: 'Disguise', isHidden: false }],
  },

  // --- GENERATION 8: GALAR ---
  {
    id: 810,
    name: 'grookey',
    displayName: 'Grookey',
    aliases: ['grookey'],
    generation: 8,
    types: ['grass'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/810.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/810.ogg',
    height: 3,
    weight: 50,
    genus: 'Chimp Pokémon',
    flavorText: 'When it uses its special stick to strike up a beat, the sound waves revitalize nearby plants.',
    stats: [
      { name: 'hp', baseStat: 50 },
      { name: 'attack', baseStat: 65 },
      { name: 'defense', baseStat: 50 },
      { name: 'special-attack', baseStat: 40 },
      { name: 'special-defense', baseStat: 40 },
      { name: 'speed', baseStat: 65 },
    ],
    abilities: [{ name: 'Overgrow', isHidden: false }],
  },
  {
    id: 813,
    name: 'scorbunny',
    displayName: 'Scorbunny',
    aliases: ['scorbunny'],
    generation: 8,
    types: ['fire'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/813.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/813.ogg',
    height: 3,
    weight: 45,
    genus: 'Rabbit Pokémon',
    flavorText: 'A warm-up of running around gets fire energy coursing through its body, boosting kick power.',
    stats: [
      { name: 'hp', baseStat: 50 },
      { name: 'attack', baseStat: 71 },
      { name: 'defense', baseStat: 40 },
      { name: 'special-attack', baseStat: 40 },
      { name: 'special-defense', baseStat: 40 },
      { name: 'speed', baseStat: 69 },
    ],
    abilities: [{ name: 'Blaze', isHidden: false }],
  },
  {
    id: 816,
    name: 'sobble',
    displayName: 'Sobble',
    aliases: ['sobble'],
    generation: 8,
    types: ['water'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/816.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/816.ogg',
    height: 3,
    weight: 40,
    genus: 'Water Lizard Pokémon',
    flavorText: 'When scared, this Pokémon cries. Its tears pack the chemical punch of 100 onions, making attackers weep.',
    stats: [
      { name: 'hp', baseStat: 50 },
      { name: 'attack', baseStat: 40 },
      { name: 'defense', baseStat: 40 },
      { name: 'special-attack', baseStat: 70 },
      { name: 'special-defense', baseStat: 40 },
      { name: 'speed', baseStat: 70 },
    ],
    abilities: [{ name: 'Torrent', isHidden: false }],
  },
  {
    id: 887,
    name: 'dragapult',
    displayName: 'Dragapult',
    aliases: ['dragapult'],
    generation: 8,
    types: ['dragon', 'ghost'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/887.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/887.ogg',
    height: 30,
    weight: 500,
    genus: 'Stealth Pokémon',
    flavorText: 'When it isn’t battling, it keeps Dreepy in the holes on its horns. In battle, it launches them like supersonic missiles.',
    stats: [
      { name: 'hp', baseStat: 88 },
      { name: 'attack', baseStat: 120 },
      { name: 'defense', baseStat: 75 },
      { name: 'special-attack', baseStat: 100 },
      { name: 'special-defense', baseStat: 75 },
      { name: 'speed', baseStat: 142 },
    ],
    abilities: [{ name: 'Clear Body', isHidden: false }, { name: 'Infiltrator', isHidden: false }],
  },

  // --- GENERATION 9: PALDEA ---
  {
    id: 906,
    name: 'sprigatito',
    displayName: 'Sprigatito',
    aliases: ['sprigatito'],
    generation: 9,
    types: ['grass'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/906.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/906.ogg',
    height: 4,
    weight: 41,
    genus: 'Grass Cat Pokémon',
    flavorText: 'Its fluffy fur is similar in composition to plants. It washes its face regularly to avoid drying out.',
    stats: [
      { name: 'hp', baseStat: 40 },
      { name: 'attack', baseStat: 61 },
      { name: 'defense', baseStat: 54 },
      { name: 'special-attack', baseStat: 45 },
      { name: 'special-defense', baseStat: 45 },
      { name: 'speed', baseStat: 65 },
    ],
    abilities: [{ name: 'Overgrow', isHidden: false }],
  },
  {
    id: 909,
    name: 'fuecoco',
    displayName: 'Fuecoco',
    aliases: ['fuecoco'],
    generation: 9,
    types: ['fire'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/909.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/909.ogg',
    height: 4,
    weight: 98,
    genus: 'Fire Croc Pokémon',
    flavorText: 'It lies on warm rocks and uses the heat absorbed by its square scales to create fire energy.',
    stats: [
      { name: 'hp', baseStat: 67 },
      { name: 'attack', baseStat: 45 },
      { name: 'defense', baseStat: 59 },
      { name: 'special-attack', baseStat: 63 },
      { name: 'special-defense', baseStat: 40 },
      { name: 'speed', baseStat: 36 },
    ],
    abilities: [{ name: 'Blaze', isHidden: false }],
  },
  {
    id: 912,
    name: 'quaxly',
    displayName: 'Quaxly',
    aliases: ['quaxly'],
    generation: 9,
    types: ['water'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/912.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/912.ogg',
    height: 5,
    weight: 61,
    genus: 'Duckling Pokémon',
    flavorText: 'This Pokémon secretes a gel from its feathers that repels water and grime. It dislikes getting dirty.',
    stats: [
      { name: 'hp', baseStat: 55 },
      { name: 'attack', baseStat: 65 },
      { name: 'defense', baseStat: 45 },
      { name: 'special-attack', baseStat: 50 },
      { name: 'special-defense', baseStat: 45 },
      { name: 'speed', baseStat: 50 },
    ],
    abilities: [{ name: 'Torrent', isHidden: false }],
  },
  {
    id: 1007,
    name: 'koraidon',
    displayName: 'Koraidon',
    aliases: ['koraidon'],
    generation: 9,
    types: ['fighting', 'dragon'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1007.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/1007.ogg',
    height: 25,
    weight: 3030,
    genus: 'Paradox Pokémon',
    flavorText: 'This seems to be the Winged King mentioned in an old expedition journal. It was said to split the land with its bare fists.',
    isLegendary: true,
    stats: [
      { name: 'hp', baseStat: 100 },
      { name: 'attack', baseStat: 135 },
      { name: 'defense', baseStat: 115 },
      { name: 'special-attack', baseStat: 85 },
      { name: 'special-defense', baseStat: 100 },
      { name: 'speed', baseStat: 135 },
    ],
    abilities: [{ name: 'Orichalcum Pulse', isHidden: false }],
  },
  {
    id: 1008,
    name: 'miraidon',
    displayName: 'Miraidon',
    aliases: ['miraidon'],
    generation: 9,
    types: ['electric', 'dragon'],
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1008.png',
    cryUrl: 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/1008.ogg',
    height: 28,
    weight: 2400,
    genus: 'Paradox Pokémon',
    flavorText: 'Much remains unknown about this creature. It resembles Cyclizar, but it is far more ruthless and formidable.',
    isLegendary: true,
    stats: [
      { name: 'hp', baseStat: 100 },
      { name: 'attack', baseStat: 85 },
      { name: 'defense', baseStat: 100 },
      { name: 'special-attack', baseStat: 135 },
      { name: 'special-defense', baseStat: 115 },
      { name: 'speed', baseStat: 135 },
    ],
    abilities: [{ name: 'Hadron Engine', isHidden: false }],
  },
];

export default POKEMON_DATABASE;
